### ISSUE TITLE
[Compatibility Request]: Cactus texture replaced with water texture with Future Commands

### ISSUE THREAD

**Issue by makamys** [FalsePattern/AnimFix#5]
### Other mod's name

Future Commands

### Other mod's homepage

https://metroidcubed.enjin.com/forum/m/51633119/viewthread/32699131-future-commands-v13-backporting-from-112-to-1710

### Other mod's license

All Rights Reserved

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/AnimFix/files/8984610/fml-client-latest.log)

### Description

When Future Commands is present, the bottom cactus texture is replaced with the still water texture. Actual still water blocks are unaffected.

![](https://user-images.githubusercontent.com/13667520/175771869-eab1dae6-72fe-4a6c-b147-944ed84a79f9.png)

Looking at the block texture atlas, it can be seen that the bottom cactus texture is missing, while the still water texture only appears once. This suggests the two blocks share the same texture slot for whatever reason.
![out-water](https://user-images.githubusercontent.com/13667520/175771991-1f0dc53c-fb08-4b5d-8ccb-aad9a2b2c503.png)

The atlas without Future Commands for reference:
![out-ok](https://user-images.githubusercontent.com/13667520/175772181-369c6d15-ad3f-41a8-b26c-69171d625a0f.png)

The issue doesn't happen with AnimFix 1.4.0, it was introduced in 1.4.1. That should narrow it down greatly.

By the way, the log is full of `Applying generic patches` lines, but this is unlikely to be related. It's just Future Commands redirecting any `GuiIngame#renderVignette` calls it finds to its own handler.

### Existing Patches

- [X] This request is not for FastCraft

**Comment by FalsePattern** [comment]
Fixed in 2.0
