### ISSUE TITLE
[1.7.10] invisible water

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/AnimFix#7]
Mods list :

animfix-mc1.7.10-2.2.0
falsepatternlib-mc1.7.10-0.10.5
SpongeMixins-1.5.0(from gtnh)

when i remove anim fix i don't get this issue
this issue does not happen with animfix-mc1.7.10-2.1.0

seed : 6072332008759161860
location : 21 112 108

logs : 
[latest.log](https://github.com/FalsePattern/AnimFix/files/9438701/latest.log)

screenshot :

when i go away

![image](https://user-images.githubusercontent.com/42176772/187048507-e05e441d-9427-4a02-bb3c-6d67aa1861a0.png)

when i get closer

![image](https://user-images.githubusercontent.com/42176772/187048539-64245fb5-e5ce-47d8-88d8-1001f59da9f1.png)

**Comment by FalsePattern** [comment]
This is a bug in the mipmap logic of animfix, it will be fixed in the next release.
In the meantime, you can set mipmap levels to 0/off in the config to fix this.
(#8 is the same bug)

**Comment by quentin452** [comment]
issue fixed in animfix-mc1.7.10-2.2.1
